### ISSUE TITLE
include source for the non-proprietary code 

### ISSUE THREAD

**Issue by MechanicalDragon0687** [blawar/lithium#14]
I understand that you have a right to closed source, but i would ask that you include some source from your app and make proprietary stuff compiled library files. This would allow the non-proprietary stuff from publicly available sources to be analyzed for trustworthiness but keep private routines (such as optimizations or proprietary encryption) to be hidden away.

I would be open to hearing why you wish to keep the entirety code completely hidden away.

Either way, it doesnt make sense to have the binaries in both source and release, might make more sense to just put it in release and leave a readme and license in the source.

**Comment by blawar** [comment]
I tried just having the binary in release, and people got confused / didnt know where to download it at.

It started out as an open source project, but then there was some drama with someone stealing other project's code, and I decided to go closed source:  https://github.com/tiliarou/sysnut
