### ISSUE TITLE
Source code is missing

### ISSUE THREAD

**Issue by NovaPhoenix** [blawar/lithium#2]
Hi, looks like you forgot to upload the source code to Lithium. It wouldn't make sense to only upload binaries to a _GitHub_ repo.

**Comment by XorTroll** [comment]
Nah, he seems to find a sense doing this.

**Comment by jerbear64** [comment]
It seems that if you are looking for drama, this may end up being drama's safer and way more extended evolution.

**Comment by pimpinpsp** [comment]
He doesn't upload the source to anything he makes. It's all part of the contract™

**Comment by joelc608** [comment]
The fact that you are using a github repo but only uploading binaries to it is misleading to the general public. Some people might take a glance at the fact that you have a github for this and then assume that its open source when in reality it is just another version of DZ tinfoil
