### ISSUE TITLE
app loads but buttons don't work

### ISSUE THREAD

**Issue by ShadwDrgn** [blawar/lithium#29]
I get in app and none of the controller buttons do anything at all. can only force close app with home button  and X on running app.

**Comment by evertonstz** [comment]
You need to enable `enable_deprecated_hid_mitm` in atmos' `system_settings.ini` file, if you don't know how a simple google search for the term and you'll find.
Cheers!

**Comment by Linkmanss** [comment]
Same problem, touch screen and home button works but don't let you install anything...

**Comment by ShadwDrgn** [comment]
I don't remember why this happened or when but i'm closing it because i ahven't had issues in a billion years
