### ISSUE TITLE
Source code missing

### ISSUE THREAD

**Issue by FaZeIlLuMiNaTi** [blawar/lithium#8]
This is pretty sketchy. I'd recommend using [XorTroll/Goldleaf](https://github.com/XorTroll/Goldleaf) because it's open source, developed by a respected member of the Switch community.

Also: this comment was edited by blawar in order to censor my original message. This is not acceptable.

**Comment by joelc608** [comment]
Goldleaf is the safer, more reliable version of Lithium

**Comment by joelc608** [comment]
Goldleaf is the safer and way more extended version of Lithium and DZ "Tinfoil"

**Comment by FaZeIlLuMiNaTi** [comment]
This issue wasn't resolved.

**Comment by joelc608** [comment]
Quit closing these Blake

**Comment by FaZeIlLuMiNaTi** [comment]
@joelc608 What was your comment before it was deleted? Abuse of censorship shouldn't be tolerated here.

**Comment by joelc608** [comment]
> 
> 
> @joelc608 What was your comment before it was deleted? Abuse of censorship shouldn't be tolerated here.

I said it's strange that there's only binaries and not source code on a GitHub repo.
And I 100% agree he is abusing censorship.
